package Domini.Model;
// Generated 16-jun-2015 1:54:28 by Hibernate Tools 4.3.1



/**
 * Usuariregistrat generated by hbm2java
 */
public class UsuariRegistrat  implements java.io.Serializable {


     private String username;
     private String nom;
     private String cognom;
     private String pwd;
     
     
    public String getPassword(){return getPwd();}
    public String getUserName(){return getUsername();}

    public UsuariRegistrat() {
    }

	
    public UsuariRegistrat(String username) {
        this.username = username;
    }
    public UsuariRegistrat(String username, String nom, String cognom, String pwd) {
       this.username = username;
       this.nom = nom;
       this.cognom = cognom;
       this.pwd = pwd;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCognom() {
        return this.cognom;
    }
    
    public void setCognom(String cognom) {
        this.cognom = cognom;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }




}


