/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio.PartidaView;

import Comunicacio.InfoCasella;
import Comunicacio.InfoPartidaNova;
import Presentacio.Comuns.BotoSortir;
import Presentacio.Comuns.Finestra;
import Presentacio.Comuns.FinestraAmbMsg;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author JOAN
 */
public class Partida extends FinestraAmbMsg {

    private Tauler Partida;
    private Controls Botons;
    private JLabel Puntuacio;
    private JLabel MillorPuntuacio;
    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();
 
    }
    public Partida(InfoPartidaNova infoPN,ActionListener TancarHandler,ActionListener Moure) {
        initComponents();
        initOwnComponents(TancarHandler,Moure,infoPN.millorPuntuacioJug);
        mostrarEstatPartida(infoPN.puntuacio,infoPN.caselles);
    }
    public void SetNumero(int Fila,int Columna,Integer Numero){
        Partida.SetNumero(Fila, Columna, Numero);
    }

    
    private void initOwnComponents(ActionListener TancarHandler,ActionListener Moure,int MillorP){
        this.setTitle("2048");
        
        setLayout(new BorderLayout());
        
        Partida = new Tauler();
        Botons = new Controls(Moure);
      
        
        Puntuacio = new JLabel("Puntuacio: 0");
        Puntuacio.setHorizontalAlignment(JLabel.CENTER);
        MillorPuntuacio = new JLabel("Millor Puntuacio: " + MillorP);
        MillorPuntuacio.setHorizontalAlignment(JLabel.CENTER);
        JPanel PanellPuntuacio = new JPanel();
        PanellPuntuacio.setLayout(new BorderLayout());
        
        JPanel PanellInterior = new JPanel();
        PanellInterior.add(Puntuacio);
        PanellInterior.add(MillorPuntuacio);
        
        PanellPuntuacio.add(PanellInterior,BorderLayout.CENTER);
        
    
        
        JPanel JocIControls = new JPanel();
        JocIControls.setLayout(new GridLayout());
        
        JocIControls.add(Partida);
        JocIControls.add(Botons);
        
        JPanel Principal = new JPanel();
        Principal.setLayout(new BorderLayout());
        
        Principal.add(PanellPuntuacio,BorderLayout.SOUTH);
        Principal.add(JocIControls,BorderLayout.CENTER);
        
        this.add(Principal,BorderLayout.CENTER);
                
        
    
        JPanel Misc = new JPanel();
        Misc.setLayout(new BorderLayout());
        
        BotoSortir Sortir = new BotoSortir(TancarHandler);
        Misc.add(Sortir,BorderLayout.EAST);
        
        this.add(Misc,BorderLayout.SOUTH);
        
        
        
        
    
    }
    public void Acabar(){
        
    }
    public void mostrarEstatPartida(int puntuacio,Set<InfoCasella> InfoC) {
        setPuntuacio(puntuacio);
        Partida.SetCaselles(InfoC);
    }
    
    private void setPuntuacio(int p){
        Puntuacio.setText("Puntuacio:" + p);
    }
    
    public String getTipusMov(){
        return Botons.getTipusMov();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

   
}
